### ISSUE TITLE
当设置有Ellipsis后会报如下错误

### ISSUE THREAD

**Issue by Witype** [hongyangAndroid/android-percent-support-extend#14]
Process: com.sophpark.upark, PID: 23962
                                                                    java.lang.ArrayIndexOutOfBoundsException: length=25; index=-1
                                                                        at android.text.StaticLayout.calculateEllipsis(StaticLayout.java:666)
                                                                        at android.text.StaticLayout.out(StaticLayout.java:630)
                                                                        at android.text.StaticLayout.generate(StaticLayout.java:423)
                                                                        at android.text.StaticLayout.<init>(StaticLayout.java:140)
                                                                        at android.widget.TextView.makeSingleLayout(TextView.java:6601)
                                                                        at android.widget.TextView.makeNewLayout(TextView.java:6446)
                                                                        at android.widget.TextView.onMeasure(TextView.java:6804)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1083)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
                                                                        at com.zhy.android.percent.support.PercentLinearLayout.onMeasure(PercentLinearLayout.java:62)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1267)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                        at android.widget.ScrollView.onMeasure(ScrollView.java:337)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2632)
                                                                        at android.view.View.measure(View.java:17536)
                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2125)
                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1238)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1455)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1126)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6041)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:596)
                                                                        at andro

**Comment by Witype** [comment]
并且Textview中被Ellipsis隐藏的部分无法显示
