### ISSUE TITLE
Caused by: java.util.IllegalFormatConversionException: %f can't format com.zhy.android.percent.support.PercentLayoutHelper$PercentLayoutInfo$PercentVal arguments

### ISSUE THREAD

**Issue by runfengai** [hongyangAndroid/android-percent-support-extend#47]
做机型适配的时候碰到这样一个错误，设备是vivo X6D。使用方式如下：
<com.zhy.android.percent.support.PercentRelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:background="#ffffff"
        android:orientation="vertical"
        app:layout_widthPercent="77%"/>
</com.zhy.android.percent.support.PercentRelativeLayout>
错误如下：
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): Caused by: java.util.IllegalFormatConversionException: %f can't format com.zhy.android.percent.support.PercentLayoutHelper$PercentLayoutInfo$PercentVal arguments
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at java.util.Formatter.badArgumentType(Formatter.java:1489)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at java.util.Formatter.transformFromFloat(Formatter.java:2038)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at java.util.Formatter.transform(Formatter.java:1465)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at java.util.Formatter.doFormat(Formatter.java:1081)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at java.util.Formatter.format(Formatter.java:1042)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at java.util.Formatter.format(Formatter.java:1011)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at java.lang.String.format(String.java:1554)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at java.lang.String.format(String.java:1528)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at com.zhy.android.percent.support.PercentLayoutHelper$PercentLayoutInfo.toString(PercentLayoutHelper.java:598)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at java.lang.StringBuilder.append(StringBuilder.java:202)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at com.zhy.android.percent.support.PercentLayoutHelper.getPercentLayoutInfo(PercentLayoutHelper.java:309)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at com.zhy.android.percent.support.PercentRelativeLayout$LayoutParams.<init>(PercentRelativeLayout.java:106)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at com.zhy.android.percent.support.PercentRelativeLayout.generateLayoutParams(PercentRelativeLayout.java:82)
08-06 19:40:34.723 E/chatSDK:c.a(Line:114)(22891): 	at com.zhy.android.percen

**Comment by runfengai** [comment]
更正下，设备不是vivo ，是美图的，型号：美图 M6s(MP1512)

**Comment by fangzhangmeipiaorou** [comment]
同样遇到此问题,在联发科cpu的ROM上就会出现
