### ISSUE TITLE
空指针异常，机型华为荣耀7i

### ISSUE THREAD

**Issue by evanwang1021** [hongyangAndroid/android-percent-support-extend#9]
FATAL EXCEPTION: main
Process: com.xxx, PID: 16022
java.lang.NullPointerException: Attempt to read from field 'float com.zhy.android.percent.support.PercentLayoutHelper$PercentLayoutInfo$PercentVal.percent' on a null object reference
at com.zhy.android.percent.support.PercentLayoutHelper.shouldHandleMeasuredHeightTooSmall(PercentLayoutHelper.java:667)
at com.zhy.android.percent.support.PercentLayoutHelper.handleMeasuredStateTooSmall(PercentLayoutHelper.java:642)
at com.zhy.android.percent.support.PercentRelativeLayout.onMeasure(PercentRelativeLayout.java:89)
at 
android.view.View.layout(View.java:15732)
at 
android.view.ViewGroup.layout(ViewGroup.java:5051)
at 
android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
at com.zhy.android.percent.support.PercentRelativeLayout.onLayout(PercentRelativeLayout.java:96)
at 
android.view.View.layout(View.java:15745)
at
android.view.ViewGroup.layout(ViewGroup.java:5051)
at 
android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at 
android.widget.FrameLayout.onLayout(FrameLayout.java:514) 
at 
android.view.View.layout(View.java:15745)
at 
android.view.ViewGroup.layout(ViewGroup.java:5051)
at 
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
at 
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
at 
android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
at 
android.view.View.layout(View.java:15745)
at 
android.view.ViewGroup.layout(ViewGroup.java:5051)
at 
android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at 
android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at 
android.view.View.layout(View.java:15745)
at 
android.view.ViewGroup.layout(ViewGroup.java:5051)
at 
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
at 
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
at 
android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
at 
android.view.View.layout(View.java:15745)
at 
android.view.ViewGroup.layout(ViewGroup.java:5051)
at 
android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at 
android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at
android.view.View.layout(View.java:15745)
at 
android.view.ViewGroup.layout(ViewGroup.java:5051)
at 
android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2153)
at 
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1907)
at
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)
at 
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6204)
at 
android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
at 
android.view.Choreographer.doCallbacks(Choreographer.java:612)
at 
android.view.Choreographer.doFrame(Choreographer.java:581)
at 
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:785)
at 
android.os.Handler.handleCallback(Handler.java:739)
at 
android.os.Handler.dispatchMessage(Handler.java:95)
at 
android.os.Looper.loop(Looper.java:135)
at 
android.app.ActivityThread.main(ActivityThread.java:5593)

**Comment by mylovemaliang** [comment]
我也出现了一样的问题，请问怎么解决的？

**Comment by JasonLinkinBright** [comment]
一样的问题＋1
